[package]
name = "ws-relay-rs"
version = "0.1.0"
authors = ["Tomoyuki Ueda <tomoyuki.ueda@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "*"
